ResearchID: this.state.ResearchID,
          ProjectName: this.state.ProjectName,
          Demographic: this.state.Demographic,
          Country: this.state.Country,
          IndustryName: this.state.IndustryName,
          Company: this.state.Company,
          Status:this.state.Status,
          Privacy_Level: this.state.Checked,
          Problem_Statement:this.state.Problem_Statement,
          Date: this.state.Date,
          KeyInsight:this.state.KeyInsight,
          KeyPainPoint: this.state.KeyPainPoint,
          Methods: this.state.Methods,
          Commentary: this.state.Commentary,
          ResearcherID:this.state.ResearcherID,
          Time_in_days: this.state.Time_Length,
          SampleSize:this.state.SampleSize,
          URL_ID:this.state.URL_ID,
          Tags:this.state.Tags
